CREATE DATABASE BD_DML (EDITION = 'basic'); -- "(EDITION = 'basic')" É PARA QUEM USAR O BD NO AZURE

USE BD_DML

CREATE TABLE TB_DML(
MATRICULA TINYINT PRIMARY KEY,
NOME VARCHAR(100) ,
SEXO CHAR(1))

ALTER TABLE TB_DML
ADD DTNASC DATETIME, CPF CHAR( 11)

ALTER TABLE TB_DML
ALTER COLUMN DTNASC DATE

ALTER TABLE TB_DML
DROP COLUMN CPF

DROP DATABASE BD_DDL
