CREATE TABLE tb_check(
COD INT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
VALOR NUMERIC (6,2) CONSTRAINT CK_VAL CHECK (VALOR > 0),
LETRA CHAR (1) CHECK (LETRA IN ('A','B','C'))
)

INSERT INTO tb_check(COD, NOME, VALOR, LETRA)
VALUES (1,'JOHNES', 10, 'A')

INSERT INTO tb_check(COD, NOME, VALOR, LETRA)
VALUES (2,'MARIA', 0, 'B')

INSERT INTO tb_check(COD, NOME, VALOR, LETRA)
VALUES (2,'MARIA', 1, 'Z')

INSERT INTO tb_check(COD, NOME, VALOR, LETRA)
VALUES (2,'MARIA', NULL, NULL)

SELECT * FROM tb_check