CREATE TABLE TB_DDL (
MATRICULA TINYINT PRIMARY KEY,
NOME VARCHAR(100),
SEXO CHAR(1)
)

ALTER TABLE TB_DDL
ADD DTNASC DATETIME, CPF CHAR(11) -- ADICIONAR DATANASC E CPF NA TABELA

ALTER TABLE TB_DDL
ADD TELEFONE CHAR(9) -- ADICIONAR COLUNA DE TELEFONE NA TABELA

ALTER TABLE TB_DDL
ALTER COLUMN DTNASC DATE --ALTERAR TIPO DE DATA PARA DATE E NÃO DATETIME

ALTER TABLE TB_DDL
DROP COLUMN SEXO -- DELETAR COLUNA DE SEXO

DROP TABLE TB_DDL -- DELETAR TABELA COMPLETA

DROP DATABASE BD_DDL -- DELETAR BANDO DE DADOS