CREATE DATABASE BD_CONSULTAS_NOITE

CREATE TABLE  TB_FUNC (
MATRICULA INT PRIMARY KEY IDENTITY,
NOME VARCHAR (255) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
SALARIO MONEY NULL,
DATAADMISSAO DATE DEFAULT (GETDATE()),
DATADEMISSAO DATE NULL,
INICIOFERIAS DATE NULL,
FIMFERIAS DATE NULL,
STATUS_FUNC VARCHAR (20) CHECK (STATUS_FUNC IN ('ATIVO','INATIVO','FERIAS','LICENÇA','INSS')),
VALOR INT)

INSERT INTO TB_FUNC (NOME, DATANASCIMENTO,SALARIO,DATAADMISSAO,DATADEMISSAO,INICIOFERIAS,FIMFERIAS, STATUS_FUNC, VALOR)
VALUES ('ANA MARIA', '2000-01-01', 1200.55, '2018-05-01',NULL,NULL,NULL, 'ATIVO', 1),
('JOSE HENRIQUE', '1998-11-20', 2575.55, '2005-09-01','2017-12-01',NULL,NULL, 'INATIVO', 7),
('ANA MARIA', '2002-08-21', 950.00, '2019-01-01',NULL,NULL,NULL, 'ATIVO', 6),
('LUAN FELIX', '1991-09-28', 3500.00, '2013-04-01',NULL,NULL,NULL, 'ATIVO', 1),
('FELIPE JOSE DOS SANTOS', '1996-01-11', 4000, '2011-05-01','2015-01-29',NULL,NULL, 'INATIVO', 2),
('MARCELO JOSE', '1980-10-05', 7000, '2000-05-01',NULL,'2019-05-01','2019-06-01', 'ATIVO', 2),
('MARIANA MARIA', '1987-02-08', 4500, '2010-01-01',NULL,NULL,NULL, 'INSS', 3),
('JULIANA MARIA DOS SANTOS', '2002-01-01', 2000, '2017-05-01',NULL,NULL,NULL, 'LICENÇA', 5),
('MARIA ALICIA', '2001-01-01', 950, '2018-05-01',NULL,NULL,NULL, 'ATIVO', 4)

------------------------------
	
INSERT INTO TB_FUNC (NOME, DATANASCIMENTO,SALARIO,STATUS_FUNC, VALOR)
VALUES ('MARIA ALICIA', '2003-09-18', 950,  'ATIVO', 3)
 
SELECT * FROM TB_FUNC ORDER BY NOME,SALARIO

SELECT * FROM TB_FUNC ORDER BY NOME DESC

SELECT * FROM TB_FUNC WHERE SALARIO >= '1000'
ORDER BY MATRICULA

SELECT * FROM TB_FUNC WHERE SALARIO > 2000 AND STATUS_FUNC = 'ATIVO'

SELECT * FROM TB_FUNC WHERE SALARIO = 1000 OR STATUS_FUNC = 'ATIVO'

SELECT * FROM TB_FUNC

SELECT NOME, SALARIO FROM TB_FUNC WHERE VALOR = 1

SELECT NOME FROM TB_FUNC WHERE NOT NOME = 'ANA MARIA'

------------------------------

SELECT NOME, SALARIO, 
SALARIO + 150, 
SALARIO - 500, 
SALARIO * 3, SALARIO / 2 ,
(SALARIO + VALOR) * 2
FROM TB_FUNC

------------------------------

SELECT * FROM TB_FUNC
WHERE DATADEMISSAO IS NULL

SELECT * FROM TB_FUNC
WHERE DATADEMISSAO IS NOT NULL

------------------------------

SELECT * FROM TB_FUNC
WHERE DATAADMISSAO BETWEEN '2012-01-01' AND '2018-04-29'

SELECT * FROM TB_FUNC
WHERE VALOR NOT BETWEEN 5 AND 15
ORDER BY VALOR

------------------------------

SELECT * FROM TB_FUNC WHERE STATUS_FUNC IN ('ATIVO','FERIAS','ATESTADO','FALECIDO')

SELECT * FROM TB_FUNC WHERE VALOR IN (1,7)

SELECT * FROM TB_FUNC WHERE MONTH(DATAADMISSAO) IN (1,2)

SELECT * FROM TB_FUNC WHERE NOME LIKE 'JOSE'

SELECT * FROM TB_FUNC WHERE NOME LIKE '%JOSE' -- BUSCA TODOS QUE COMEÇA COM NOME JOSE

SELECT * FROM TB_FUNC WHERE NOME LIKE 'JOSE%' -- BUSCA TODOS QUE TERMINA COM NOME JOSE

SELECT * FROM TB_FUNC WHERE NOME LIKE '%JOSE%' -- BUSCA TODOS QUE TENHA JOSE NO INICIO, MEIO, FIM COM NOME JOSE

------------------------------

SELECT -- AS (ALIAS)
F.NOME AS 'NOME DO FUNCIONÁRIO',
F.DATAADMISSAO AS 'DATA DE ADMISSÃO',
F.STATUS_FUNC AS 'STATUS DO FUNCIONÁRIO'
FROM TB_FUNC AS F -- COMO SE FOSSE TRANSFORMAR UMA COLUNO NUM OBJETO

------------------------------

SELECT F.NOME, F.STATUS_FUNC, -- CASE
CASE F.STATUS_FUNC
	WHEN 'ATIVO' THEN 'A'
	WHEN 'INATIVO' THEN 'I'
	WHEN 'FERIAS' THEN 'F'
	WHEN 'LICENÇA' THEN 'L'
ELSE
	'O'
END AS SIGLA_STATUS
FROM TB_FUNC AS F

-----------------------------

SELECT NOME, SALARIO, -- CASE 2
CASE
	WHEN SALARIO > 1200 AND SALARIO < 1500 THEN SALARIO * 1.1
	WHEN SALARIO > 1501 AND SALARIO < 2000 THEN SALARIO * 1.2
END SALARIO_COM_REAJUSTE
FROM TB_FUNC

-----------------------------

SELECT DISTINCT NOME FROM TB_FUNC -- RETORNA APENAS UM OCORRENCIA A NIVEL DE CONSULTA (ELIMINA DUPLICATAS)

SELECT DISTINCT NOME, SALARIO FROM TB_FUNC

-----------------------------

SELECT TOP 5 MATRICULA,NOME FROM TB_FUNC -- TOP 5 MATRICULAS, NOME (ORDEM DE INSERÇÃO)

SELECT TOP 5 MATRICULA,NOME,SALARIO FROM TB_FUNC
ORDER BY SALARIO ASC -- TOP 5 MENORES SALARIOS

SELECT TOP 5 MATRICULA,NOME,SALARIO FROM TB_FUNC
ORDER BY SALARIO DESC -- TOP 5 MAIORES SALARIOS
