CREATE DATABASE BD_AGREGACAO_NOITE
GO

CREATE TABLE PRODUTO(
CODIGO INT PRIMARY KEY IDENTITY,
CATEGORIA VARCHAR(100),
TIPO VARCHAR(100),
NOME VARCHAR(100),
PRECO MONEY,
QTD_ESTOQUE INT)

INSERT INTO PRODUTO(CATEGORIA,TIPO,NOME,PRECO,QTD_ESTOQUE)
VALUES ('COZINHA',	'ARMARIO',	'ARMARIO MOGNO A1',	240.5,	10),
('COZINHA',	'ELETRODOMESTICO',	'GELADEIRA BRASTEMP 400 L',	1500.50,	5),
('INFORMATICA',	'SMARTPHONE',	'LG K10 POWER',	750.00, 50),
('INFORMATICA',	'NOTEBOOK',	'ACER GAMER I7',	7500.00,	3),
('INFORMATICA',	'NOTEBOOK',	'DELL I7 16 GB',	5800.00,	1),
('AUTOMOTIVO',	'PNEU',	'FIRESTON ARO 14',	199.99,	100),
('AUTOMOTIVO',	'PNEU',	'PIRELI ARO 16',	339.99,	100),
('AUTOMOTIVO',	'PNEU',	'MICHELAN ARO 15',	449.99,	50),
('INFORMATICA',	'SMARTPHONE',	'IOS 10'	,7000,	50),
('INFORMATICA',	'CONSOLE',	'PS 4',	2000,	20),
('INFORMATICA',	'CONSOLE',	'XBOX',	2200,	60),
('COZINHA',	'ELETRODOMESTICO',	'FOGÃO 8 BOCAS BRASTEMP',	1500,	240),
('INFORMATICA', 	'ULTRABOOK',	'SAMSUNG I7 8GB',	3571,	NULL)

SELECT * FROM PRODUTO

SELECT
COUNT(*) AS CONTA_TUDO,
COUNT (QTD_ESTOQUE) AS IGNORA_NULOS
FROM PRODUTO

SELECT
CATEGORIA,
NOME,
PRECO
FROM PRODUTO
WHERE CATEGORIA = 'AUTOMOTIVO'

SELECT SUM(PRECO) SOMANDO_PRECOS
FROM PRODUTO
WHERE CATEGORIA = 'AUTOMOTIVO'

SELECT
MAX(QTD_ESTOQUE)
MAIOR_ESTOQUE
FROM
PRODUTO

SELECT
MIN(QTD_ESTOQUE)
MENOR_ESTOQUE
FROM
PRODUTO

SELECT
SUM (QTD_ESTOQUE) / COUNT (PRECO) MEDIA_AUTOMOTIVO1,
AVG(QTD_ESTOQUE) MEDIA_AUTOMOTIVO
FROM PRODUTO
WHERE CATEGORIA = 'AUTOMOTIVO'

SELECT
CATEGORIA,
SUM (QTD_ESTOQUE) AS QTD_ESTOQUE_AUTOMOTIVO
FROM PRODUTO
GROUP BY CATEGORIA
