CREATE DATABASE BD_JOINS_NOITE
GO

USE BD_JOINS_NOITE
GO

CREATE TABLE DEPARTAMENTO (
CODIGO INT PRIMARY KEY IDENTITY,
DESCRICAO VARCHAR(100) NOT NULL
)
GO

CREATE TABLE FUNCAO (
CODIGO INT PRIMARY KEY IDENTITY,
DESCRICAO VARCHAR(100)
)

CREATE TABLE FUNCIONARIO (
MATRICULA INT PRIMARY KEY IDENTITY,
NOME VARCHAR(255) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
CPF CHAR(11) UNIQUE CHECK (LEN(CPF) = 11),
SALARIO MONEY NULL,
DATAADMISSAO DATE DEFAULT (GETDATE()),
DATADEMISSAO DATE NULL,
INICIOFERIAS DATE NULL,
FIMFERIAS DATE NULL,
STATUS_FUNC VARCHAR(20) CHECK (STATUS_FUNC IN ('ATIVO','INATIVO','FERIAS','LICENÇA','INSS')),
CODDEPTO INT FOREIGN KEY REFERENCES DEPARTAMENTO (CODIGO),
CODSUPERVISOR INT FOREIGN KEY REFERENCES FUNCIONARIO (MATRICULA),
CODFUNCAO INT FOREIGN KEY REFERENCES FUNCAO (CODIGO)
)
GO

sp_rename 'FUNCIONARIO.DATAEMISSAO', 'DATAADMISSAO', 'COLUMN'; --ALTERAR NOME DE UMA TABELA, 
--SEQUÊNCIA: ('TABELA.NOMEDACOLUNAATUAL' , 'NOMEDATABELANOVO', 'COLUMN(PALAVRA CHAVE)'


SELECT * FROM FUNCIONARIO

INSERT INTO DEPARTAMENTO
VALUES ('TECNOLOGIA DA INFORMACAO'),
('RECURSOS HUMANOS'),
('JURIDICO'),('SELEÇÃO'),
('CONTABILIDADE'),
('CONTAS A PAGAR E RECEBER'),
('DEPARTAMENTO PESSOAL')
GO

INSERT INTO FUNCAO
VALUES ('ESTAGIARIO'), ('ANALISTA JR'),('ANALISTA PL'),('ANALISTA SR'),('COORDENADOR'),('GERENTE')
GO

INSERT INTO FUNCIONARIO (NOME, DATANASCIMENTO,CPF, SALARIO,DATAADMISSAO,DATADEMISSAO,INICIOFERIAS,FIMFERIAS, STATUS_FUNC,
CODDEPTO, CODSUPERVISOR, CODFUNCAO)
VALUES
('ANA MARIA', '2000-01-01','12345678911', 1200.55, '2018-05-01',NULL,NULL,NULL, 'ATIVO', 1, 6, 2 ),
('JOSE HENRIQUE', '1998-11-20','12345678912', 2575.55, '2005-09-01','2017-12-01',NULL,NULL, 'INATIVO', 7, NULL, 3 ),
('ANA MARIA', '2002-08-21','12345678913', 950.00, '2019-01-01',NULL,NULL,NULL, 'ATIVO', 6, NULL, 1),
('LUAN FELIX', '1991-09-28','12345678914', 3500.00, '2013-04-01',NULL,NULL,NULL, 'ATIVO', 3,NULL,2),
('FELIPE JOSE DOS SANTOS', '1996-01-11','12345678915', 4000, '2011-05-01','2015-01-29',NULL,NULL, 'INATIVO', 2, NULL, 3),
('MARCELO JOSE', '1980-10-05','12345678916', 7000, '2000-05-01',NULL,'2019-05-01','2019-06-01', 'ATIVO', 1, NULL, 1),
('MARIANA MARIA', '1987-02-08','12345678917', 4500, '2010-01-01',NULL,NULL,NULL, 'INSS', 1, 6, 3 ),
('JULIANA MARIA DOS SANTOS', '2002-01-01','12345678918', 2000, '2017-05-01',NULL,NULL,NULL, 'LICENÇA', 5, NULL, 2 ),
('MARIA ALICIA', '2001-01-01','12345678919', 950, '2018-05-01',NULL,NULL,NULL, 'ATIVO', 1, 6, 1)
GO
INSERT INTO FUNCIONARIO (NOME, DATANASCIMENTO,CPF, SALARIO,STATUS_FUNC, CODDEPTO,CODSUPERVISOR,CODFUNCAO)
VALUES ('MARIA ALICIA', '2003-09-18','12345678920', 950, 'ATIVO', NULL, NULL,1)

SELECT * FROM FUNCIONARIO

SELECT * FROM DEPARTAMENTO
SELECT * FROM FUNCAO
SELECT * FROM FUNCIONARIO
ORDER BY CODDEPTO
--------------------- INNER JOIN
SELECT
F.NOME,
F.CODDEPTO,
D.DESCRICAO AS 'DEPARTAMENTO DO FUNCIONARIO'

FROM FUNCIONARIO AS F
	INNER JOIN DEPARTAMENTO AS D
	ON F.CODDEPTO = D.CODIGO

---------------------- LEFT JOIN
SELECT
F.NOME,
F.MATRICULA,
D.DESCRICAO AS 'DEPARTAMENTO DO FUNCIONARIO',
FUN.DESCRICAO AS 'FUNCAO'

FROM FUNCIONARIO AS F
		
	LEFT JOIN DEPARTAMENTO AS D
	ON F.CODDEPTO = D.CODIGO

	INNER JOIN FUNCAO AS FUN
	ON FUN.CODIGO = F.CODFUNCAO

----------------------- RIGHT JOIN

SELECT
F.NOME,
F.MATRICULA,
D.DESCRICAO AS 'DEPARTAMENTO DO FUNCIONARIO',
FUN.DESCRICAO AS 'FUNCAO'

FROM FUNCIONARIO AS F
		
	RIGHT JOIN DEPARTAMENTO AS D
	ON F.CODDEPTO = D.CODIGO

	LEFT JOIN FUNCAO AS FUN
	ON FUN.CODIGO = F.CODFUNCAO

------------------------ FULL JOIN

SELECT
F.NOME,
F.MATRICULA,
D.DESCRICAO AS 'DEPARTAMENTO DO FUNCIONARIO'

FROM FUNCIONARIO AS F
		
	FULL JOIN DEPARTAMENTO AS D
	ON F.CODDEPTO = D.CODIGO

------------------------ SELF JOIN
SELECT
F.NOME AS FUNCIONARIO,
S.NOME AS SUPERVISOR
FROM FUNCIONARIO AS F		
	LEFT JOIN FUNCIONARIO AS S
	ON F.CODSUPERVISOR = S.MATRICULA
	
-------------------------

@@@@@@@@@@@@@@@@@@@@@@@@@@@@
CREATE
TABLE ALUNO(
MATRICULA INT PRIMARY KEY,
NOME VARCHAR(20)
)

CREATE TABLE DISCIPLINA(
CODDISC CHAR(3) PRIMARY KEY,
DESCRICAO VARCHAR(20)
)

INSERT INTO ALUNO (MATRICULA, NOME)
VALUES (100,'ALUNO A'), (150,'ALUNO B')

INSERT INTO DISCIPLINA (CODDISC, DESCRICAO)
VALUES ('PBD','PROG EM BD'),('POO','PROG ORIENT A OBJ')

CREATE TABLE ALUNO_DISCIPLINA
(
PK_ALUNO_DISCIPLINA INT PRIMARY KEY IDENTITY,
FK_MATRICULA INT FOREIGN KEY REFERENCES ALUNO(MATRICULA),
FK_CODDISC CHAR(3) FOREIGN KEY REFERENCES DISCIPLINA(CODDISC),
)

INSERT
INTO ALUNO_DISCIPLINA (FK_CODDISC,FK_MATRICULA)
VALUES ('PBD',100), ('POO', 100), ('POO', 150)

SELECT
A.MATRICULA,
D.DESCRICAO
FROM ALUNO AS A
	INNER JOIN ALUNO_DISCIPLINA AS AD
	ON A.MATRICULA = AD.FK_MATRICULA
	INNER JOIN DISCIPLINA AS D
	ON AD.FK_CODDISC = D.CODDISC
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@