CREATE DATABASE BD_UNIAO_CONSULTAS
GO
USE BD_UNIAO_CONSULTAS
GO
CREATE TABLE A(
    ID INT NOT NULL,
    NOME VARCHAR(10) NOT NULL
)

CREATE TABLE B(
    ID INT NOT NULL,
    NOME VARCHAR(10) NOT NULL
)


INSERT INTO A VALUES (1, 'José'), (2, 'Maria'), (3, 'João')
INSERT INTO B VALUES (2, 'Maria'), (3, 'Guilherme'), (4, 'Vitória')

--UNION 

SELECT ID, NOME FROM A
UNION
SELECT ID, NOME FROM B

--UNION ALL
SELECT ID, NOME FROM A
UNION ALL
SELECT ID, NOME FROM B

--EXCEPT

(
SELECT ID, NOME FROM A
EXCEPT
SELECT ID, NOME FROM B
)

UNION ALL

(
SELECT ID, NOME FROM B
EXCEPT
SELECT ID, NOME FROM A
)

-- INTERSECT

SELECT ID, NOME FROM A
INTERSECT
SELECT ID, NOME FROM B