CREATE TABLE tb_unique(
Cod INT PRIMARY KEY,
Nome VARCHAR(50),
CPF CHAR(11) CONSTRAINT UQ_CPF UNIQUE
)
-- CERTO
INSERT INTO tb_unique(Cod, Nome, CPF)
VALUES (1, 'ATENA','11122233300'), (2, 'MAY','11122233301'), (3, 'PRINCESA',NULL)

SELECT * FROM tb_unique

-- ERRADO
INSERT INTO tb_unique(Cod, Nome, CPF)
VALUES (4, 'ATENA',NULL)

CREATE TABLE tb_unique2(
Cod INT PRIMARY KEY,
Nome VARCHAR(50) UNIQUE,
CPF CHAR(11)
)